<?php

$qt_alphabet = [
    'a' => ['type' => 'vowel', 'soft' => false],
    'b' => ['type' => 'consonant', 'sonorous' => true],
    'c' => ['type' => 'consonant', 'sonorous' => true],
    'ç' => ['type' => 'consonant', 'sonorous' => false],
    'd' => ['type' => 'consonant', 'sonorous' => true],
    'e' => ['type' => 'vowel', 'soft' => true],
    'f' => ['type' => 'consonant', 'sonorous' => false],
    'g' => ['type' => 'consonant', 'sonorous' => true],
    'ğ' => ['type' => 'consonant', 'sonorous' => true],
    'h' => ['type' => 'consonant', 'sonorous' => false],
    'ı' => ['type' => 'vowel', 'soft' => false],
    'i' => ['type' => 'vowel', 'soft' => true ],
    'İ' => ['type' => 'vowel', 'soft' => true ],
    'j' => ['type' => 'consonant', 'sonorous' => true ],
    'k' => ['type' => 'consonant', 'sonorous' => false ],
    'l' => ['type' => 'consonant', 'sonorous' => true],
    'm' => ['type' => 'consonant', 'sonorous' => true],
    'n' => ['type' => 'consonant', 'sonorous' => true],
    'ñ' => ['type' => 'consonant', 'sonorous' => true],
    'o' => ['type' => 'vowel', 'soft' => false],
    'ö' => ['type' => 'vowel', 'soft' => true],
    'p' => ['type' => 'consonant', 'sonorous' => false],
    'q' => ['type' => 'consonant', 'sonorous' => false],
    'r' => ['type' => 'consonant', 'sonorous' => true],
    's' => ['type' => 'consonant', 'sonorous' => false],
    'ş' => ['type' => 'consonant', 'sonorous' => false],
    't' => ['type' => 'consonant', 'sonorous' => false],
    'u' => ['type' => 'vowel', 'soft' => false],
    'ü' => ['type' => 'vowel', 'soft' => true],
    'v' => ['type' => 'consonant', 'sonorous' => true],
    'y' => ['type' => 'consonant', 'sonorous' => true],
    'z' => ['type' => 'consonant', 'sonorous' => true],
    'â' => ['type' => 'vowel', 'soft' => true]
];
